# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-ndk
    resource_class: medium+
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      SDK_FILENAME: sdk-tools-linux-4333796.zip
      ANDROID_HOME: /opt/android/sdk

    steps:
      - checkout

      # Download and cache dependencies gradle
      - restore_cache:
          keys:
            - fabriik-dependencies-{{ checksum "brd-android/build.gradle.kts" }}-{{ checksum "brd-android/app/build.gradle.kts" }}

      # Pull submodules
      - run:
          name: Pull submodules
          command: |
            git submodule update --init --recursive

      # Refresh gradle
      - run:
          name: Refresh gradle
          command: |
            ./gradlew   dependencies

      # Unit tests
      - run:
          name: Run unit tests
          command: |
            ./gradlew  --console=plain  testBrdTestnetDebugUnitTest

      # Generate Jacoco report
      - run:
          name: Generate Jacoco report
          command: |
            ./gradlew  --console=plain :brd-android:app:jacocoTestReport

      # save cache
      - save_cache:
          key: fabriik-dependencies-{{ checksum "brd-android/build.gradle.kts" }}-{{ checksum "brd-android/app/build.gradle.kts" }}
          paths:
            - ~/.gradle

      # save reports
      - run:
          name: Save test reports
          command: |
            mkdir -p ~/reports
            ls -l ./brd-android/app/build
            cp -r ./brd-android/app/build/reports ~/reports;
            cp -r ./brd-android/app/build/test-results ~/reports;
            cp -r ./brd-android/app/build/outputs ~/reports;
          when: always
      - store_test_results:
          path: ./brd-android/app/build/test-results
      - store_artifacts:
          path: ~/reports
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only:
                - rok/ci