# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-ndk
    resource_class: medium+
    working_directory: ~/brd-mobile

    environment:
      # Customize the JVM maximum heap limit
      SDK_FILENAME: sdk-tools-linux-4333796.zip
      ANDROID_HOME: /opt/android/sdk

    steps:
      - checkout

      # Download and cache dependencies gradle
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "brd-android/build.gradle.kts" }}-{{ checksum "brd-android/app/build.gradle.kts" }}
            - v1-flutter-sdk-{{ checksum "brd-android/kyc-flutter/.metadata" }}

      # Pull submodules
      - run:
          name: Pull submodules
          command: |
            git submodule update --init --recursive

      # Setup Flutter SDK
      - run:
          name: Setup Flutter SDK
          command: |
            export PATH="$PATH:$(pwd)/flutter-sdk/bin"

            # check if flutter-sdk folder exist
            if [ ! -d flutter-sdk ]; then
              export TARGET_SDK_COMMIT=$(awk '/revision:/ {print $2}' brd-android/kyc-flutter/.metadata)
              git clone https://github.com/flutter/flutter.git flutter-sdk
              cd flutter-sdk
              git checkout TARGET_SDK_COMMIT
              cd ..
              flutter precache
              flutter doctor
            fi

            cd brd-android/kyc-flutter
            flutter clean
            flutter pub get

      # save cache - Flutter SDK
      - save_cache:
          name: Saving cache - Flutter SDK
          key: v1-flutter-sdk-{{ checksum "brd-android/kyc-flutter/.metadata" }}
          paths:
            - flutter-sdk

      # Refresh gradle
      - run:
          name: Refresh gradle
          command: |
            ./gradlew   dependencies

      # save cache - Gradle
      - save_cache:
          name: Saving cache - Gradle
          key: v1-dependencies-{{ checksum "brd-android/build.gradle.kts" }}-{{ checksum "brd-android/app/build.gradle.kts" }}
          paths:
            - ~/.gradle

      # Unit tests
      - run:
          name: Run unit tests
          command: |
            ./gradlew  --console=plain  testBrdTestnetDebugUnitTest

      # Generate Jacoco report
      - run:
          name: Generate Jacoco report
          command: |
            ./gradlew  --console=plain :brd-android:app:jacocoTestReport

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only:
                - rok/ci