# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-ndk
    resource_class: medium+
    working_directory: ~/brd-mobile

    environment:
      # Customize the JVM maximum heap limit
      SDK_FILENAME: sdk-tools-linux-4333796.zip
      ANDROID_HOME: /opt/android/sdk

    steps:
      - checkout

      # Get last Flutter SDK commit hash
      - run:
          name: Get last Flutter SDK commit
          command: |
            LAST_COMMIT=$(git ls-remote https://github.com/flutter/flutter.git HEAD | awk '{ print $1}')
            echo 'export FLUTTER_SDK_LAST_COMMIT=$LAST_COMMIT' >> $BASH_ENV
            source $BASH_ENV
            echo $FLUTTER_SDK_LAST_COMMIT

      # Download and cache dependencies gradle
      - restore_cache:
          keys:
            - fabriik-dependencies-{{ checksum "brd-android/build.gradle.kts" }}-{{ checksum "brd-android/app/build.gradle.kts" }}
            - flutter-sdk-{{ .Environment.FLUTTER_SDK_LAST_COMMIT }}

      # Pull submodules
      - run:
          name: Pull submodules
          command: |
            git submodule update --init --recursive

      # Setup Flutter SDK
      - run:
          name: Setup Flutter SDK
          command: |
            git clone https://github.com/flutter/flutter.git flutter-sdk
            export PATH="$PATH:$(pwd)/flutter-sdk/bin"
            flutter precache
            flutter doctor
            cd brd-android/kyc-flutter
            flutter clean
            flutter pub get

      # save cache
      - save_cache:
          key: flutter-sdk-{{ .Environment.FLUTTER_SDK_LAST_COMMIT }}
          paths:
            - flutter-sdk

      # Refresh gradle
      - run:
          name: Refresh gradle
          command: |
            ./gradlew   dependencies

      # Unit tests
      - run:
          name: Run unit tests
          command: |
            ./gradlew  --console=plain  testBrdTestnetDebugUnitTest

      # Generate Jacoco report
      - run:
          name: Generate Jacoco report
          command: |
            ./gradlew  --console=plain :brd-android:app:jacocoTestReport

      # save cache
      - save_cache:
          key: fabriik-dependencies-{{ checksum "brd-android/build.gradle.kts" }}-{{ checksum "brd-android/app/build.gradle.kts" }}
          paths:
            - ~/.gradle

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only:
                - rok/ci