# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-29-ndk
    resource_class: medium+
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      SDK_FILENAME: sdk-tools-linux-4333796.zip
      ANDROID_HOME: /opt/android/sdk

    steps:
      - checkout

      # Download and cache dependencies gradle
      - restore_cache:
          keys:
            - fabriik-dependencies-{{ checksum "brd-android/build.gradle" }}-{{ checksum "brd-android/app/build.gradle" }}

      # Pull submodules
      - run:
          name: Pull submodules
          command: |
            git submodule update --init --recursive

      #Refresh gradle
      - run:
          name: Refresh gradle
          command: |
            ./gradlew   dependencies

      #gradle build
      - run:
          name: gradle assembleBrdTestnetDebug
          command: |
            ./gradlew  --console=plain  assembleBrdTestnetDebug

      # save cache
      - save_cache:
          key: fabriik-dependencies-{{ checksum "brd-android/build.gradle" }}-{{ checksum "brd-android/app/build.gradle" }}
          paths:
            - ~/.gradle

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only:
                - rok/ci